services:
  app:
    build:
      context: .
    restart: unless-stopped
    ports:
       - "3000"
    environment:
      NODE_ENV: production
      DATABASE_PATH: /app/data/prcs-it.db
      AUTH_SECRET: ${AUTH_SECRET}
      LOCAL_AUTH_SETUP_TOKEN: ${LOCAL_AUTH_SETUP_TOKEN}
    volumes:
      - prcs_it_data:/app/data

volumes:
  prcs_it_data:
