"use client";
import {useMemo,useState} from "react";
import {apiFetch} from "../lib/supabase-client";

type Named={id:number;name:string};
type Child=Named&{parentId:number};
type Asset={id:number;code:string;product:string;category:string;facility:string;department:string;responsible:string;status:string;condition:string;serial:string;createdAt?:string};

export default function AssetsScreen({assets,facilities,departments,isSystemAdmin,onDeleted}:{assets:Asset[];facilities:Named[];departments:Child[];isSystemAdmin:boolean;onDeleted:(id:number)=>void}){
 const[search,setSearch]=useState(""),[facility,setFacility]=useState("الكل"),[department,setDepartment]=useState("الكل"),[responsible,setResponsible]=useState("الكل"),[status,setStatus]=useState("الكل"),[condition,setCondition]=useState("الكل"),[error,setError]=useState(""),[deleting,setDeleting]=useState<number|null>(null);
 const facilityDepartments=useMemo(()=>facility==="الكل"?departments:departments.filter(d=>d.parentId===facilities.find(f=>f.name===facility)?.id),[facility,departments,facilities]);
 const people=useMemo(()=>[...new Set(assets.filter(a=>(facility==="الكل"||a.facility===facility)&&(department==="الكل"||a.department===department)).map(a=>a.responsible).filter(Boolean))],[assets,facility,department]);
 const rows=useMemo(()=>assets.filter(a=>(facility==="الكل"||a.facility===facility)&&(department==="الكل"||a.department===department)&&(responsible==="الكل"||a.responsible===responsible)&&(status==="الكل"||a.status===status)&&(condition==="الكل"||a.condition===condition)&&Object.values(a).join(" ").toLowerCase().includes(search.toLowerCase())),[assets,facility,department,responsible,status,condition,search]);
 const clear=()=>{setSearch("");setFacility("الكل");setDepartment("الكل");setResponsible("الكل");setStatus("الكل");setCondition("الكل")};
 const remove=async(asset:Asset)=>{if(!confirm(`هل تريد حذف العهدة «${asset.code}»؟ سيتم حذف سجلات الحركة والصيانة والجرد المرتبطة بها، ولا يمكن التراجع عن ذلك.`))return;setDeleting(asset.id);setError("");try{const r=await apiFetch("/api/assets",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({id:asset.id})}),d=await r.json();if(!r.ok)throw new Error(d.error||"تعذر حذف العهدة");onDeleted(asset.id)}catch(e){setError(e instanceof Error?e.message:"تعذر حذف العهدة")}finally{setDeleting(null)}};
 return <section className="assetsPage">
  <div className="assetSummary"><article><span>إجمالي العهد</span><strong>{assets.length}</strong></article><article><span>نتائج البحث</span><strong>{rows.length}</strong></article><article><span>المرافق المسجلة</span><strong>{new Set(assets.map(a=>a.facility)).size}</strong></article><article><span>المسؤولون</span><strong>{new Set(assets.map(a=>a.responsible)).size}</strong></article></div>
  <section className="panel filterPanel"><div className="filterTitle"><div><h2>البحث والتصفية</h2><p>اعرض العهد حسب الموقع أو القسم أو الشخص المسؤول</p></div><button onClick={clear}>↻ مسح الفلاتر</button></div><div className="filterGrid assetFilters"><label className="filterSearch">بحث عام<div>⌕<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="رقم العهدة، المنتج، الرقم التسلسلي..."/></div></label><label>المرفق<select value={facility} onChange={e=>{setFacility(e.target.value);setDepartment("الكل");setResponsible("الكل")}}><option>الكل</option>{facilities.map(f=><option key={f.id}>{f.name}</option>)}</select></label><label>القسم<select value={department} onChange={e=>{setDepartment(e.target.value);setResponsible("الكل")}}><option>الكل</option>{facilityDepartments.map(d=><option key={d.id}>{d.name}</option>)}</select></label><label>المسؤول<select value={responsible} onChange={e=>setResponsible(e.target.value)}><option>الكل</option>{people.map(p=><option key={p}>{p}</option>)}</select></label><label>التشغيل<select value={status} onChange={e=>setStatus(e.target.value)}><option>الكل</option><option>يعمل</option><option>بحاجة متابعة</option><option>قيد الصيانة</option></select></label><label>حالة العهدة<select value={condition} onChange={e=>setCondition(e.target.value)}><option>الكل</option><option>جديد</option><option>مستخدم</option></select></label></div></section>
  {error&&<div className="setupError">⚠ {error}</div>}
  <section className="panel assetsPanel fullAssets"><div className="panelHead assetsHead"><div><h2>سجل الأصول والعهد</h2><p>تم العثور على {rows.length} عهدة</p></div><span className="resultPill">{rows.length} نتيجة</span></div><div className="tableWrap"><table><thead><tr><th>رقم العهدة</th><th>المنتج</th><th>الصنف</th><th>المرفق</th><th>القسم</th><th>المسؤول</th><th>حالة العهدة</th><th>التشغيل</th>{isSystemAdmin&&<th>إجراء</th>}</tr></thead><tbody>{rows.map(a=><tr key={a.id}><td><strong className="code">{a.code}</strong><small>{a.serial}</small></td><td><strong>{a.product}</strong></td><td>{a.category}</td><td>{a.facility}</td><td>{a.department}</td><td><span className="personCell">{a.responsible.slice(0,1)}</span><strong>{a.responsible}</strong></td><td><span className={`conditionBadge ${a.condition==="جديد"?"new":"used"}`}>{a.condition||"جديد"}</span></td><td><span className={`badge ${a.status==="يعمل"?"ok":a.status==="قيد الصيانة"?"repair":"follow"}`}>● {a.status}</span></td>{isSystemAdmin&&<td><button className="assetDelete" disabled={deleting===a.id} onClick={()=>remove(a)} title="حذف العهدة">{deleting===a.id?"…":"⌫"}</button></td>}</tr>)}</tbody></table>{rows.length===0&&<div className="emptyState"><strong>لا توجد نتائج مطابقة</strong><span>جرّبي تعديل الفلاتر أو مسحها.</span></div>}</div><div className="assetFoot"><span>عرض {rows.length} من أصل {assets.length} عهدة</span></div></section>
 </section>;
}
