"use client";
import SearchableSelect from "./SearchableSelect";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {apiFetch} from "../lib/api-client";
type Named={id:number;name:string;assetType?:string};type Child=Named&{parentId:number};
export type Asset={id:number;code:string;product:string;category:string;assetType?:string;facility:string;department:string;responsible:string;status:string;condition:string;serial:string;createdAt?:string};
type Maintenance={id:number;assetId:number;assetCode:string;assetName:string;issue:string;technician:string;status:string;cost:number;notes:string;createdAt:string};
type Check={id:number;assetId:number;assetCode:string;assetName:string;facility:string;department:string;result:string;checkedBy:string;notes:string;checkedAt:string};
type Stock={id:number;product:string;productId:number|null;category:string;transactionType:string;quantity:number;facility:string;reference:string;notes:string;createdAt:string};
type Plan={id:number;facilityName:string;departmentName:string;categoryName:string;productName:string;assetType:string;requiredQuantity:number;actualQuantity:number;shortage:number;surplus:number;createdAt:string};
const date=(v:string)=>new Date(v+(/Z|[+-]\d\d:?\d\d$/.test(v)?"":"Z")).toLocaleDateString("ar-PS");
async function save(url:string,payload:Record<string,unknown>){const r=await apiFetch(url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}),d=await r.json();if(!r.ok)throw new Error(d.error||"تعذر الحفظ");return d}

export function MaintenanceScreen({assets,onStatus}:{assets:Asset[];onStatus:(id:number,status:string)=>void}){const[records,setRecords]=useState<Maintenance[]>([]),[msg,setMsg]=useState("");useEffect(()=>{apiFetch("/api/maintenance").then(r=>r.json()).then(d=>setRecords(d.records||[])).catch(()=>{})},[]);const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form);try{const d=await save("/api/maintenance",{assetId:Number(f.get("assetId")),issue:f.get("issue"),technician:f.get("technician"),status:f.get("status"),cost:Number(f.get("cost")),notes:f.get("notes")});setRecords(v=>[d.record,...v]);onStatus(d.record.assetId,d.assetStatus);setMsg("تم حفظ بلاغ الصيانة وتحديث حالة الجهاز");form.reset()}catch(x){setMsg(x instanceof Error?x.message:"تعذر الحفظ")}};return <OperationPage title="سجل الصيانة" stats={[['إجمالي البلاغات',records.length],['مفتوحة',records.filter(x=>x.status==='مفتوح').length],['قيد التنفيذ',records.filter(x=>x.status==='قيد التنفيذ').length],['مكتملة',records.filter(x=>x.status==='مكتمل').length]]}><OperationForm title="إضافة بلاغ صيانة" onSubmit={submit} message={msg}><label>الجهاز<SearchableSelect name="assetId" required>{assets.map(a=><option key={a.id} value={a.id}>{a.code} — {a.product}</option>)}</SearchableSelect></label><label>وصف العطل<input name="issue" required placeholder="مثال: الجهاز لا يعمل"/></label><div className="opTwo"><label>الفني المسؤول<input name="technician" placeholder="اسم الفني"/></label><label>الحالة<SearchableSelect name="status"><option>مفتوح</option><option>قيد التنفيذ</option><option>مكتمل</option></SearchableSelect></label></div><label>التكلفة التقديرية (شيكل)<input name="cost" type="number" min="0" defaultValue="0"/></label><label>ملاحظات<textarea name="notes"/></label></OperationForm><Records title="بلاغات الصيانة"><table><thead><tr><th>الجهاز</th><th>العطل</th><th>الفني</th><th>الحالة</th><th>التكلفة</th><th>التاريخ</th></tr></thead><tbody>{records.map(r=><tr key={r.id}><td><strong className="code">{r.assetCode}</strong><small>{r.assetName}</small></td><td>{r.issue}</td><td>{r.technician||'—'}</td><td><span className={`badge ${r.status==='مكتمل'?'ok':r.status==='قيد التنفيذ'?'follow':'repair'}`}>{r.status}</span></td><td>{r.cost} ₪</td><td>{date(r.createdAt)}</td></tr>)}</tbody></table></Records></OperationPage>}

export function InventoryScreen({assets,facilities}:{assets:Asset[];facilities:Named[]}){const[checks,setChecks]=useState<Check[]>([]),[facility,setFacility]=useState("الكل"),[msg,setMsg]=useState("");useEffect(()=>{apiFetch("/api/inventory").then(r=>r.json()).then(d=>setChecks(d.checks||[])).catch(()=>{})},[]);const visible=facility==='الكل'?checks:checks.filter(x=>x.facility===facility);const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form);try{const d=await save("/api/inventory",{assetId:Number(f.get("assetId")),result:f.get("result"),checkedBy:f.get("checkedBy"),notes:f.get("notes")});setChecks(v=>[d.check,...v]);setMsg("تم اعتماد نتيجة الجرد وحفظها");form.reset()}catch(x){setMsg(x instanceof Error?x.message:"تعذر الحفظ")}};return <OperationPage title="الجرد الميداني" stats={[['الأصول المسجلة',assets.length],['تم جردها',new Set(checks.map(x=>x.assetId)).size],['موجود',checks.filter(x=>x.result==='موجود').length],['مفقود/تالف',checks.filter(x=>x.result==='مفقود'||x.result==='تالف').length]]}><OperationForm title="تسجيل نتيجة جرد" onSubmit={submit} message={msg}><label>الجهاز<SearchableSelect name="assetId" required>{assets.map(a=><option key={a.id} value={a.id}>{a.code} — {a.product} — {a.facility}</option>)}</SearchableSelect></label><div className="opTwo"><label>نتيجة الجرد<SearchableSelect name="result"><option>موجود</option><option>مفقود</option><option>تالف</option><option>بحاجة متابعة</option></SearchableSelect></label><label>اسم المدقق<input name="checkedBy" required placeholder="اسم منفذ الجرد"/></label></div><label>ملاحظات<textarea name="notes" placeholder="مكان الجهاز الفعلي أو الملاحظات"/></label></OperationForm><Records title="نتائج الجرد" action={<SearchableSelect value={facility} onChange={e=>setFacility(e.target.value)}><option>الكل</option>{facilities.map(f=><option key={f.id}>{f.name}</option>)}</SearchableSelect>}><table><thead><tr><th>الجهاز</th><th>المرفق</th><th>القسم</th><th>النتيجة</th><th>المدقق</th><th>التاريخ</th></tr></thead><tbody>{visible.map(r=><tr key={r.id}><td><strong className="code">{r.assetCode}</strong><small>{r.assetName}</small></td><td>{r.facility}</td><td>{r.department}</td><td><span className={`badge ${r.result==='موجود'?'ok':r.result==='بحاجة متابعة'?'follow':'repair'}`}>{r.result}</span></td><td>{r.checkedBy}</td><td>{date(r.checkedAt)}</td></tr>)}</tbody></table></Records></OperationPage>}

export function ReportsScreen({assets,facilities,categories}:{assets:Asset[];facilities:Named[];categories:Named[]}){
 const[facility,setFacility]=useState("الكل"),[category,setCategory]=useState("الكل"),[assetType,setAssetType]=useState("الكل"),[department,setDepartment]=useState("الكل"),[status,setStatus]=useState("الكل"),[condition,setCondition]=useState("الكل"),[query,setQuery]=useState(""),[dateFrom,setDateFrom]=useState(""),[dateTo,setDateTo]=useState(""),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(10),[needPage,setNeedPage]=useState(1),[plans,setPlans]=useState<Plan[]>([]),[maintenance,setMaintenance]=useState<Maintenance[]>([]),[checks,setChecks]=useState<Check[]>([]),[stock,setStock]=useState<Stock[]>([]);
 useEffect(()=>{Promise.all([apiFetch("/api/maintenance").then(r=>r.json()),apiFetch("/api/inventory").then(r=>r.json()),apiFetch("/api/stock").then(r=>r.json()),apiFetch("/api/planning").then(r=>r.json())]).then(([m,i,s,p])=>{setMaintenance(m.records||[]);setChecks(i.checks||[]);setStock(s.transactions||[]);setPlans(p.plans||[])})},[]);
 const departments=useMemo(()=>Array.from(new Set(assets.filter(asset=>facility==="الكل"||asset.facility===facility).map(asset=>asset.department).filter(Boolean))).sort((a,b)=>a.localeCompare(b,"ar")),[assets,facility]);
 const filtered=useMemo(()=>assets.filter(asset=>{
  const text=`${asset.code} ${asset.serial} ${asset.product} ${asset.category} ${asset.facility} ${asset.department} ${asset.responsible}`.toLocaleLowerCase();
  const created=asset.createdAt?new Date(asset.createdAt).getTime():null;
  const from=dateFrom?new Date(`${dateFrom}T00:00:00`).getTime():null;
  const to=dateTo?new Date(`${dateTo}T23:59:59`).getTime():null;
  return (facility==="الكل"||asset.facility===facility)&&(category==="الكل"||asset.category===category)&&(assetType==="الكل"||(asset.assetType||categories.find(item=>item.name===asset.category)?.assetType||"تقني")===assetType)&&(department==="الكل"||asset.department===department)&&(status==="الكل"||asset.status===status)&&(condition==="الكل"||asset.condition===condition)&&(!query.trim()||text.includes(query.trim().toLocaleLowerCase()))&&(!from||(created!==null&&created>=from))&&(!to||(created!==null&&created<=to));
 }),[assets,facility,category,assetType,department,status,condition,query,dateFrom,dateTo,categories]);
 useEffect(()=>setPage(1),[facility,category,assetType,department,status,condition,query,dateFrom,dateTo,pageSize]);
 const pages=Math.max(1,Math.ceil(filtered.length/pageSize));
 useEffect(()=>{if(page>pages)setPage(pages)},[page,pages]);
 const pageItems=filtered.slice((page-1)*pageSize,page*pageSize);
 const pageNumbers=useMemo(()=>{const values:(number|string)[]=[];for(let number=1;number<=pages;number++){if(number===1||number===pages||Math.abs(number-page)<=1)values.push(number);else if(values[values.length-1]!=="…")values.push("…")}return values},[page,pages]);
 const startItem=filtered.length?(page-1)*pageSize+1:0,endItem=Math.min(page*pageSize,filtered.length);
 const activeFilters=[facility,category,assetType,department,status,condition].filter(value=>value!=="الكل").length+(query?1:0)+(dateFrom?1:0)+(dateTo?1:0);
 const categoryStats=categories.map(item=>({item,count:filtered.filter(asset=>asset.category===item.name).length})).filter(item=>item.count>0).sort((a,b)=>b.count-a.count).slice(0,10);
 const filteredPlans=useMemo(()=>plans.filter(plan=>(facility==="الكل"||plan.facilityName===facility)&&(category==="الكل"||plan.categoryName===category)&&(assetType==="الكل"||plan.assetType===assetType)&&(department==="الكل"||plan.departmentName===department)&&(!query.trim()||`${plan.productName} ${plan.categoryName} ${plan.facilityName} ${plan.departmentName}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()))),[plans,facility,category,assetType,department,query]);
 useEffect(()=>setNeedPage(1),[facility,category,assetType,department,query,pageSize]);
 const needPages=Math.max(1,Math.ceil(filteredPlans.length/pageSize)),needItems=filteredPlans.slice((needPage-1)*pageSize,needPage*pageSize);
 useEffect(()=>{if(needPage>needPages)setNeedPage(needPages)},[needPage,needPages]);
 const needNumbers=useMemo(()=>{const values:(number|string)[]=[];for(let number=1;number<=needPages;number++){if(number===1||number===needPages||Math.abs(number-needPage)<=1)values.push(number);else if(values[values.length-1]!=="…")values.push("…")}return values},[needPage,needPages]);
 const resetFilters=()=>{setFacility("الكل");setCategory("الكل");setAssetType("الكل");setDepartment("الكل");setStatus("الكل");setCondition("الكل");setQuery("");setDateFrom("");setDateTo("")};
 const exportCsv=()=>{const head="رقم العهدة,الجهاز,الصنف,النوع,المرفق,القسم,المسؤول,الحالة,حالة الجهاز,تاريخ التسجيل\n",body=filtered.map(asset=>[asset.code,asset.product,asset.category,asset.assetType||categories.find(item=>item.name===asset.category)?.assetType||"تقني",asset.facility,asset.department,asset.responsible,asset.status,asset.condition,asset.createdAt||""].map(value=>`"${String(value).replaceAll('"','""')}"`).join(",")).join("\n"),url=URL.createObjectURL(new Blob(["\ufeff"+head+body],{type:"text/csv"})),link=document.createElement("a");link.href=url;link.download="it-assets-report.csv";link.click();URL.revokeObjectURL(url)};
 return <section className="reportsPage">
  <div className="reportHeader"><div><h2>تقارير الأصول والعهد</h2><p>فلترة وتحليل وتصدير بيانات الأجهزة المسجلة في النظام</p></div><div><button onClick={exportCsv}>↓ تصدير Excel/CSV</button><button className="primary" onClick={()=>window.print()}>▣ طباعة التقرير</button></div></div>
  <div className="panel reportFilters">
   <div className="reportFilterTitle"><div><h3>فلاتر التقرير</h3><p>يمكن الجمع بين أكثر من فلتر للوصول إلى النتائج المطلوبة</p></div><span>{activeFilters} فلاتر مفعّلة</span></div>
   <div className="reportFilterGrid">
    <label className="reportSearchField"><span>البحث</span><div className="search">⌕<input value={query} onChange={event=>setQuery(event.target.value)} placeholder="رقم العهدة، الجهاز، المسؤول..."/></div></label>
    <label><span>نوع الأجهزة</span><SearchableSelect value={assetType} onChange={event=>setAssetType(event.target.value)}><option>الكل</option><option>تقني</option><option>طبي</option></SearchableSelect></label>
    <label><span>الصنف</span><SearchableSelect value={category} onChange={event=>setCategory(event.target.value)}><option>الكل</option>{categories.filter(item=>assetType==="الكل"||(item.assetType||"تقني")===assetType).map(item=><option key={item.id}>{item.name}</option>)}</SearchableSelect></label>
    <label><span>المرفق</span><SearchableSelect value={facility} onChange={event=>{setFacility(event.target.value);setDepartment("الكل")}}><option>الكل</option>{facilities.map(item=><option key={item.id}>{item.name}</option>)}</SearchableSelect></label>
    <label><span>القسم</span><SearchableSelect value={department} onChange={event=>setDepartment(event.target.value)}><option>الكل</option>{departments.map(item=><option key={item}>{item}</option>)}</SearchableSelect></label>
    <label><span>الحالة التشغيلية</span><SearchableSelect value={status} onChange={event=>setStatus(event.target.value)}><option>الكل</option><option>يعمل</option><option>بحاجة متابعة</option><option>قيد الصيانة</option></SearchableSelect></label>
    <label><span>حالة الجهاز</span><SearchableSelect value={condition} onChange={event=>setCondition(event.target.value)}><option>الكل</option><option>جديد</option><option>مستخدم</option></SearchableSelect></label>
    <label><span>من تاريخ</span><input type="date" value={dateFrom} onChange={event=>setDateFrom(event.target.value)}/></label>
    <label><span>إلى تاريخ</span><input type="date" value={dateTo} min={dateFrom||undefined} onChange={event=>setDateTo(event.target.value)}/></label>
   </div>
   <div className="reportFilterActions"><strong>{filtered.length} نتيجة</strong><button type="button" onClick={resetFilters} disabled={!activeFilters}>إعادة ضبط الفلاتر</button></div>
  </div>
  <div className="assetSummary"><article><span>إجمالي النتائج</span><strong>{filtered.length}</strong></article><article><span>أجهزة تعمل</span><strong>{filtered.filter(asset=>asset.status==="يعمل").length}</strong></article><article><span>قيد الصيانة</span><strong>{filtered.filter(asset=>asset.status==="قيد الصيانة").length}</strong></article><article><span>بحاجة متابعة</span><strong>{filtered.filter(asset=>asset.status==="بحاجة متابعة").length}</strong></article></div>
  <div className="reportGrid"><Records title="أعلى التصنيفات ضمن النتائج"><div className="reportBars">{categoryStats.map(({item,count})=><div key={item.id}><span>{item.name}</span><i><b style={{width:`${filtered.length?Math.max(4,count/filtered.length*100):0}%`}}/></i><strong>{count}</strong></div>)}{!categoryStats.length&&<p className="reportNoData">لا توجد بيانات لعرضها</p>}</div></Records><Records title="ملخص تشغيلي"><div className="reportSummary"><p><span>بلاغات الصيانة</span><strong>{maintenance.length}</strong></p><p><span>عمليات الجرد</span><strong>{checks.length}</strong></p><p><span>حركات المخزون</span><strong>{stock.length}</strong></p><p><span>نتائج جرد مفقودة/تالفة</span><strong>{checks.filter(item=>item.result==="مفقود"||item.result==="تالف").length}</strong></p></div></Records></div>
  <Records title="تقرير الأصول التفصيلي"><table><thead><tr><th>رقم العهدة</th><th>الجهاز</th><th>الصنف</th><th>النوع</th><th>المرفق</th><th>القسم</th><th>المسؤول</th><th>الحالة</th></tr></thead><tbody>{pageItems.map(asset=><tr key={asset.id}><td><strong className="code">{asset.code}</strong><small>{asset.serial}</small></td><td>{asset.product}</td><td>{asset.category}</td><td><span className={`typeBadge ${(asset.assetType||categories.find(item=>item.name===asset.category)?.assetType)==="طبي"?"medical":"technical"}`}>{asset.assetType||categories.find(item=>item.name===asset.category)?.assetType||"تقني"}</span></td><td>{asset.facility}</td><td>{asset.department}</td><td>{asset.responsible}</td><td><span className={`badge ${asset.status==="يعمل"?"ok":asset.status==="قيد الصيانة"?"repair":"follow"}`}>{asset.status}</span></td></tr>)}</tbody></table>{!pageItems.length&&<div className="reportNoRows">لا توجد سجلات مطابقة للفلاتر المحددة</div>}<div className="reportPager"><span>عرض {startItem}–{endItem} من {filtered.length}</span><label>عدد العناصر في الصفحة<SearchableSelect value={pageSize} onChange={event=>setPageSize(Number(event.target.value))}><option value="10">10</option><option value="20">20</option><option value="50">50</option><option value="100">100</option></SearchableSelect></label><div><button type="button" disabled={page===1} onClick={()=>setPage(page-1)}>السابق</button>{pageNumbers.map((item,index)=>item==="…"?<span key={`gap-${index}`}>…</span>:<button type="button" className={page===item?"active":""} key={item} onClick={()=>setPage(Number(item))}>{item}</button>)}<button type="button" disabled={page===pages} onClick={()=>setPage(page+1)}>التالي</button></div></div></Records>
  <section className="needReportSection"><div className="needReportHead"><div><h2>تقرير الاحتياج والعجز</h2><p>المطلوب والموجود فعليًا والعجز حسب الفلاتر المحددة</p></div><div><span>المطلوب <strong>{filteredPlans.reduce((sum,item)=>sum+item.requiredQuantity,0)}</strong></span><span>الموجود <strong>{filteredPlans.reduce((sum,item)=>sum+item.actualQuantity,0)}</strong></span><span className="shortageText">العجز <strong>{filteredPlans.reduce((sum,item)=>sum+item.shortage,0)}</strong></span></div></div><Records title="تفاصيل الاحتياج"><table><thead><tr><th>الجهاز</th><th>الصنف</th><th>النوع</th><th>المرفق</th><th>القسم</th><th>المطلوب</th><th>الموجود</th><th>العجز</th></tr></thead><tbody>{needItems.map(item=><tr key={item.id}><td><strong>{item.productName}</strong></td><td>{item.categoryName}</td><td><span className={`typeBadge ${item.assetType==="طبي"?"medical":"technical"}`}>{item.assetType}</span></td><td>{item.facilityName}</td><td>{item.departmentName}</td><td><strong>{item.requiredQuantity}</strong></td><td>{item.actualQuantity}</td><td><span className={item.shortage?"shortageNumber":"okNumber"}>{item.shortage}</span></td></tr>)}</tbody></table>{!needItems.length&&<div className="reportNoRows">لا توجد بيانات احتياج مطابقة للفلاتر</div>}<div className="reportPager"><span>عرض {filteredPlans.length?(needPage-1)*pageSize+1:0}–{Math.min(needPage*pageSize,filteredPlans.length)} من {filteredPlans.length}</span><div><button type="button" disabled={needPage===1} onClick={()=>setNeedPage(needPage-1)}>السابق</button>{needNumbers.map((item,index)=>item==="…"?<span key={`need-gap-${index}`}>…</span>:<button type="button" className={needPage===item?"active":""} key={item} onClick={()=>setNeedPage(Number(item))}>{item}</button>)}<button type="button" disabled={needPage===needPages} onClick={()=>setNeedPage(needPage+1)}>التالي</button></div></div></Records></section>
 </section>
}

function OperationPage({stats,children}:{title:string;stats:[string,number][];children:React.ReactNode}){return <section className="operationPage"><div className="assetSummary">{stats.map(([l,n])=><article key={l}><span>{l}</span><strong>{n}</strong></article>)}</div><div className="operationGrid">{children}</div></section>}
function OperationForm({title,onSubmit,message,children}:{title:string;onSubmit:(e:FormEvent<HTMLFormElement>)=>void;message:string;children:React.ReactNode}){return <form className="panel operationForm" onSubmit={onSubmit}><div className="panelHead"><div><h2>{title}</h2><p>أدخل البيانات ثم احفظ السجل</p></div><span className="moveIcon">＋</span></div>{children}{message&&<div className="formMessage">{message}</div>}<button className="primary">حفظ السجل</button></form>}
function Records({title,action,children}:{title:string;action?:React.ReactNode;children:React.ReactNode}){return <article className="panel recordsPanel"><div className="panelHead"><div><h2>{title}</h2><p>البيانات المحفوظة في النظام</p></div>{action}</div><div className="tableWrap">{children}</div></article>}
