"use client";
import SearchableSelect from "./SearchableSelect";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {apiFetch} from "../lib/api-client";

type Named={id:number;name:string;assetType?:string};
type Child=Named&{parentId:number};
type Allocation={key:number;facilityId:number;departmentId:number;requiredQuantity:number};
type Plan={id:number;facilityId:number;departmentId:number;categoryId:number;productId:number;facilityName:string;departmentName:string;categoryName:string;productName:string;assetType:string;requiredQuantity:number;actualQuantity:number;shortage:number;surplus:number;notes:string};

export default function PlanningScreen({facilities,departments,categories,products}:{facilities:Named[];departments:Child[];categories:Named[];products:Child[]}){
 const firstCategory=categories[0]?.id||0;
 const makeAllocation=(key=Date.now()):Allocation=>{const facilityId=facilities[0]?.id||0;return{key,facilityId,departmentId:departments.find(x=>x.parentId===facilityId)?.id||0,requiredQuantity:0}};
 const[plans,setPlans]=useState<Plan[]>([]),[categoryId,setCategoryId]=useState(firstCategory),[productId,setProductId]=useState(products.find(x=>x.parentId===firstCategory)?.id||0),[allocations,setAllocations]=useState<Allocation[]>([makeAllocation()]),[type,setType]=useState("الكل"),[facilityFilter,setFacilityFilter]=useState("الكل"),[categoryFilter,setCategoryFilter]=useState("الكل"),[productFilter,setProductFilter]=useState("الكل"),[departmentFilter,setDepartmentFilter]=useState("الكل"),[shortageFilter,setShortageFilter]=useState("الكل"),[planSearch,setPlanSearch]=useState(""),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(10),[editing,setEditing]=useState<Plan|null>(null),[message,setMessage]=useState(""),[saving,setSaving]=useState(false);
 const load=()=>apiFetch("/api/planning").then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setPlans(d.plans||[])}).catch(e=>setMessage(e instanceof Error?e.message:"تعذر التحميل"));
 useEffect(()=>{void load()},[]);
 useEffect(()=>{if(products.some(x=>x.id===productId&&x.parentId===categoryId))return;const first=products.find(x=>x.parentId===categoryId);setProductId(first?.id||0)},[categoryId,products,productId]);
 const chooseProduct=(id:number)=>{const chosen=products.find(x=>x.id===id);setProductId(id);if(chosen)setCategoryId(chosen.parentId)};
 const visible=useMemo(()=>plans.filter(x=>(type==="الكل"||x.assetType===type)&&(facilityFilter==="الكل"||x.facilityName===facilityFilter)&&(categoryFilter==="الكل"||x.categoryName===categoryFilter)&&(productFilter==="الكل"||x.productName===productFilter)&&(departmentFilter==="الكل"||x.departmentName===departmentFilter)&&(shortageFilter==="الكل"||(shortageFilter==="عجز"&&x.shortage>0)||(shortageFilter==="مكتمل"&&x.shortage===0))&&(!planSearch.trim()||`${x.productName} ${x.categoryName} ${x.facilityName} ${x.departmentName}`.toLocaleLowerCase().includes(planSearch.trim().toLocaleLowerCase()))),[plans,type,facilityFilter,categoryFilter,productFilter,departmentFilter,shortageFilter,planSearch]);
 const totals=visible.reduce((a,x)=>({need:a.need+x.requiredQuantity,actual:a.actual+x.actualQuantity,shortage:a.shortage+x.shortage,surplus:a.surplus+x.surplus}),{need:0,actual:0,shortage:0,surplus:0});
 const enteredTotal=allocations.reduce((sum,x)=>sum+(Number(x.requiredQuantity)||0),0);
 const categoryOptions=useMemo(()=>Array.from(new Set(plans.filter(x=>type==="الكل"||x.assetType===type).map(x=>x.categoryName))).sort((a,b)=>a.localeCompare(b)),[plans,type]);
 const productOptions=useMemo(()=>Array.from(new Set(plans.filter(x=>(type==="الكل"||x.assetType===type)&&(categoryFilter==="الكل"||x.categoryName===categoryFilter)).map(x=>x.productName))).sort((a,b)=>a.localeCompare(b)),[plans,type,categoryFilter]);
 const departmentOptions=useMemo(()=>Array.from(new Set(plans.filter(x=>facilityFilter==="الكل"||x.facilityName===facilityFilter).map(x=>x.departmentName))).sort((a,b)=>a.localeCompare(b)),[plans,facilityFilter]);
 const pages=Math.max(1,Math.ceil(visible.length/pageSize)),pagedPlans=visible.slice((page-1)*pageSize,page*pageSize);
 useEffect(()=>setPage(1),[type,facilityFilter,categoryFilter,productFilter,departmentFilter,shortageFilter,planSearch,pageSize]);
 useEffect(()=>{if(page>pages)setPage(pages)},[page,pages]);
 const pageNumbers=useMemo(()=>{const values:(number|string)[]=[];for(let number=1;number<=pages;number++){if(number===1||number===pages||Math.abs(number-page)<=1)values.push(number);else if(values[values.length-1]!=="…")values.push("…")}return values},[page,pages]);
 const resetFilters=()=>{setType("الكل");setFacilityFilter("الكل");setCategoryFilter("الكل");setProductFilter("الكل");setDepartmentFilter("الكل");setShortageFilter("الكل");setPlanSearch("")};
 const updateAllocation=(key:number,patch:Partial<Allocation>)=>setAllocations(current=>current.map(row=>{if(row.key!==key)return row;const next={...row,...patch};if(patch.facilityId!==undefined)next.departmentId=departments.find(x=>x.parentId===patch.facilityId)?.id||0;return next}));
 const addAllocation=()=>setAllocations(current=>[...current,makeAllocation(Date.now()+current.length)]);
 const removeAllocation=(key:number)=>setAllocations(current=>current.length===1?[makeAllocation()]:current.filter(x=>x.key!==key));
 const resetForm=()=>{setAllocations([makeAllocation()]);setMessage("")};
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setMessage("");if(!productId||allocations.some(x=>!x.facilityId||!x.departmentId||!Number.isInteger(Number(x.requiredQuantity))||Number(x.requiredQuantity)<=0)){setMessage("أكمل المرفق والقسم وأدخل رقم احتياج أكبر من صفر لكل سطر");return}const duplicate=new Set<string>();for(const row of allocations){const key=`${row.facilityId}-${row.departmentId}`;if(duplicate.has(key)){setMessage("لا يمكن تكرار المرفق والقسم لنفس الجهاز داخل الطلب");return}duplicate.add(key)}setSaving(true);try{const r=await apiFetch("/api/planning",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({categoryId,productId,allocations:allocations.map(({facilityId,departmentId,requiredQuantity})=>({facilityId,departmentId,requiredQuantity:Number(requiredQuantity)}))})}),d=await r.json();if(!r.ok)throw new Error(d.error||"تعذر حفظ الاحتياج");setPlans(d.plans);setAllocations([makeAllocation()]);setMessage(`تم حفظ احتياج الجهاز بإجمالي ${enteredTotal}`)}catch(error){setMessage(error instanceof Error?error.message:"تعذر حفظ الاحتياج")}finally{setSaving(false)}};
 const update=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!editing)return;const f=new FormData(e.currentTarget),r=await apiFetch("/api/planning",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:editing.id,requiredQuantity:Number(f.get("requiredQuantity")),notes:f.get("notes")})}),d=await r.json();if(!r.ok){setMessage(d.error);return}setPlans(d.plans);setEditing(null)};
 const remove=async(id:number)=>{if(!confirm("حذف احتياج هذا المرفق والقسم؟"))return;const r=await apiFetch("/api/planning",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({id})});if(r.ok)setPlans(v=>v.filter(x=>x.id!==id))};
 return <section className="planningPage">
  <div className="assetSummary planningSummary"><article><span>إجمالي الاحتياج</span><strong>{totals.need}</strong></article><article><span>الموجود فعليًا</span><strong>{totals.actual}</strong></article><article><span>العجز</span><strong>{totals.shortage}</strong></article><article><span>الفائض</span><strong>{totals.surplus}</strong></article></div>
  <form className="panel groupedPlanningForm" onSubmit={submit}>
   <div className="panelHead"><div><h2>إضافة احتياج مجمّع</h2><p>اختر الجهاز مرة واحدة، ثم أضف المرافق والأقسام والكميات المطلوبة.</p></div><span className="planningTotalBadge">الإجمالي: <strong>{enteredTotal}</strong></span></div>
   <div className="planningItemSelectors"><label>الصنف<SearchableSelect value={categoryId} onChange={e=>setCategoryId(Number(e.target.value))}>{categories.map(x=><option value={x.id} key={x.id}>{x.name} — {x.assetType||"تقني"}</option>)}</SearchableSelect></label><label>الجهاز<SearchableSelect className="planningDeviceSelect" value={productId} onChange={e=>chooseProduct(Number(e.target.value))} required>{products.map(x=>{const category=categories.find(item=>item.id===x.parentId);return <option value={x.id} key={x.id}>{x.name} — {category?.name||"تصنيف غير محدد"} — {category?.assetType||x.assetType||"نوع غير محدد"}</option>})}</SearchableSelect></label></div>
   <div className="allocationHead"><span>المرفق</span><span>القسم</span><span>العدد المطلوب</span><span></span></div>
   <div className="allocationRows">{allocations.map((row,index)=><div className="allocationRow" key={row.key}><SearchableSelect aria-label={`المرفق ${index+1}`} value={row.facilityId} onChange={e=>updateAllocation(row.key,{facilityId:Number(e.target.value)})}>{facilities.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</SearchableSelect><SearchableSelect aria-label={`القسم ${index+1}`} value={row.departmentId} onChange={e=>updateAllocation(row.key,{departmentId:Number(e.target.value)})} required><option value="">اختر القسم</option>{departments.filter(x=>x.parentId===row.facilityId).map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</SearchableSelect><input aria-label={`العدد المطلوب ${index+1}`} type="number" min="1" value={row.requiredQuantity||""} onChange={e=>updateAllocation(row.key,{requiredQuantity:Number(e.target.value)})} required placeholder="0"/><button type="button" className="allocationRemove" onClick={()=>removeAllocation(row.key)} title="حذف السطر">×</button></div>)}</div>
   <div className="groupedPlanningActions"><button type="button" className="addAllocation" onClick={addAllocation}>＋ إضافة مرفق وقسم</button><span>إجمالي الاحتياج المدخل: <strong>{enteredTotal}</strong></span><button type="button" onClick={resetForm}>مسح</button><button className="primary" disabled={saving||!productId}>{saving?"جاري الحفظ...":"حفظ الاحتياج"}</button></div>{message&&<p className="formMessage">{message}</p>}
  </form>
  <article className="panel recordsPanel planningRecords groupedPlanningRecords">
   <div className="panelHead"><div><h2>خطة الاحتياج حسب الأصناف والأجهزة</h2><p>عرض موحد للاحتياج المسجل حسب الجهاز والمرفق والقسم.</p></div><span className="resultPill">{visible.length} سجل احتياج</span></div>
   <div className="planningFilterPanel">
    <label className="planningSearch"><span>البحث</span><div className="search">⌕<input value={planSearch} onChange={e=>setPlanSearch(e.target.value)} placeholder="ابحث باسم الجهاز، الصنف، المرفق أو القسم..."/></div></label>
    <label><span>النوع</span><SearchableSelect value={type} onChange={e=>{setType(e.target.value);setCategoryFilter("الكل");setProductFilter("الكل")}}><option>الكل</option><option>تقني</option><option>طبي</option></SearchableSelect></label>
    <label><span>الصنف</span><SearchableSelect value={categoryFilter} onChange={e=>{setCategoryFilter(e.target.value);setProductFilter("الكل")}}><option>الكل</option>{categoryOptions.map(value=><option key={value}>{value}</option>)}</SearchableSelect></label>
    <label><span>الجهاز</span><SearchableSelect value={productFilter} onChange={e=>setProductFilter(e.target.value)}><option>الكل</option>{productOptions.map(value=><option key={value}>{value}</option>)}</SearchableSelect></label>
    <label><span>المرفق</span><SearchableSelect value={facilityFilter} onChange={e=>{setFacilityFilter(e.target.value);setDepartmentFilter("الكل")}}><option>الكل</option>{facilities.map(x=><option key={x.id}>{x.name}</option>)}</SearchableSelect></label>
    <label><span>القسم</span><SearchableSelect value={departmentFilter} onChange={e=>setDepartmentFilter(e.target.value)}><option>الكل</option>{departmentOptions.map(value=><option key={value}>{value}</option>)}</SearchableSelect></label>
    <label><span>حالة الاحتياج</span><SearchableSelect value={shortageFilter} onChange={e=>setShortageFilter(e.target.value)}><option>الكل</option><option value="عجز">يوجد عجز</option><option value="مكتمل">مكتمل بدون عجز</option></SearchableSelect></label>
    <button type="button" className="resetPlanningFilters" onClick={resetFilters}>إعادة ضبط الفلاتر</button>
   </div>
   <div className="tableWrap planningTableWrap"><table className="planningNeedTable"><thead><tr><th>النوع</th><th>الصنف</th><th>الجهاز</th><th>المرفق</th><th>القسم</th><th>المطلوب</th><th>الموجود</th><th>العجز</th><th>الإجراءات</th></tr></thead><tbody>{pagedPlans.map(x=><tr key={x.id}><td><span className={`typeBadge ${x.assetType==="طبي"?"medical":"technical"}`}>{x.assetType}</span></td><td>{x.categoryName}</td><td><strong className="planningDeviceCell">{x.productName}</strong></td><td>{x.facilityName}</td><td>{x.departmentName}</td><td><strong>{x.requiredQuantity}</strong></td><td>{x.actualQuantity}</td><td><span className={x.shortage?"shortageNumber":"okNumber"}>{x.shortage}</span></td><td><span className="rowActions"><button onClick={()=>setEditing(x)} title="تعديل">✎</button><button className="deleteAction" onClick={()=>remove(x.id)} title="حذف">⌫</button></span></td></tr>)}</tbody></table>{!visible.length&&<div className="emptyState"><strong>لا توجد نتائج مطابقة</strong><span>غيّر الفلاتر أو أضف احتياجًا جديدًا.</span></div>}</div>
   <div className="planningPager"><span>عرض {visible.length?(page-1)*pageSize+1:0}–{Math.min(page*pageSize,visible.length)} من {visible.length} سجل</span><label>عدد السجلات في الصفحة<SearchableSelect value={pageSize} onChange={e=>setPageSize(Number(e.target.value))}><option value="5">5</option><option value="10">10</option><option value="20">20</option><option value="50">50</option></SearchableSelect></label><div><button type="button" disabled={page===1} onClick={()=>setPage(page-1)}>السابق</button>{pageNumbers.map((item,index)=>item==="…"?<span key={`gap-${index}`}>…</span>:<button type="button" className={page===item?"active":""} key={item} onClick={()=>setPage(Number(item))}>{item}</button>)}<button type="button" disabled={page===pages} onClick={()=>setPage(page+1)}>التالي</button></div></div>
  </article>
  {editing&&<div className="overlay" onMouseDown={()=>setEditing(null)}><form className="modal editDefinition" onSubmit={update} onMouseDown={e=>e.stopPropagation()}><div className="modalHead"><div><h2>تعديل الاحتياج</h2><p>{editing.productName} — {editing.facilityName} / {editing.departmentName}</p></div><button type="button" onClick={()=>setEditing(null)}>×</button></div><label>العدد المطلوب<input name="requiredQuantity" type="number" min="1" defaultValue={editing.requiredQuantity} required/></label><label>ملاحظات<textarea name="notes" defaultValue={editing.notes}/></label><div className="modalActions"><button type="button" onClick={()=>setEditing(null)}>إلغاء</button><button className="primary">حفظ</button></div></form></div>}
 </section>
}
