"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {apiFetch} from "../lib/api-client";

type Named={id:number;name:string;assetType?:string};
type Child=Named&{parentId:number};
type Allocation={key:number;facilityId:number;departmentId:number;requiredQuantity:number};
type Plan={id:number;facilityId:number;departmentId:number;categoryId:number;productId:number;facilityName:string;departmentName:string;categoryName:string;productName:string;assetType:string;requiredQuantity:number;actualQuantity:number;shortage:number;surplus:number;notes:string};

export default function PlanningScreen({facilities,departments,categories,products}:{facilities:Named[];departments:Child[];categories:Named[];products:Child[]}){
 const firstCategory=categories[0]?.id||0;
 const makeAllocation=(key=Date.now()):Allocation=>{const facilityId=facilities[0]?.id||0;return{key,facilityId,departmentId:departments.find(x=>x.parentId===facilityId)?.id||0,requiredQuantity:0}};
 const[plans,setPlans]=useState<Plan[]>([]),[categoryId,setCategoryId]=useState(firstCategory),[productId,setProductId]=useState(products.find(x=>x.parentId===firstCategory)?.id||0),[allocations,setAllocations]=useState<Allocation[]>([makeAllocation()]),[type,setType]=useState("الكل"),[facilityFilter,setFacilityFilter]=useState("الكل"),[editing,setEditing]=useState<Plan|null>(null),[message,setMessage]=useState(""),[saving,setSaving]=useState(false);
 const load=()=>apiFetch("/api/planning").then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setPlans(d.plans||[])}).catch(e=>setMessage(e instanceof Error?e.message:"تعذر التحميل"));
 useEffect(()=>{void load()},[]);
 useEffect(()=>{const first=products.find(x=>x.parentId===categoryId);setProductId(first?.id||0)},[categoryId,products]);
 const visible=useMemo(()=>plans.filter(x=>(type==="الكل"||x.assetType===type)&&(facilityFilter==="الكل"||x.facilityName===facilityFilter)),[plans,type,facilityFilter]);
 const totals=visible.reduce((a,x)=>({need:a.need+x.requiredQuantity,actual:a.actual+x.actualQuantity,shortage:a.shortage+x.shortage,surplus:a.surplus+x.surplus}),{need:0,actual:0,shortage:0,surplus:0});
 const enteredTotal=allocations.reduce((sum,x)=>sum+(Number(x.requiredQuantity)||0),0);
 const groups=useMemo(()=>{const result=new Map<number,{productId:number;productName:string;categoryName:string;assetType:string;rows:Plan[];required:number;actual:number;shortage:number;surplus:number}>();for(const plan of visible){const group=result.get(plan.productId)||{productId:plan.productId,productName:plan.productName,categoryName:plan.categoryName,assetType:plan.assetType,rows:[],required:0,actual:0,shortage:0,surplus:0};group.rows.push(plan);group.required+=plan.requiredQuantity;group.actual+=plan.actualQuantity;group.shortage+=plan.shortage;group.surplus+=plan.surplus;result.set(plan.productId,group)}return[...result.values()]},[visible]);
 const updateAllocation=(key:number,patch:Partial<Allocation>)=>setAllocations(current=>current.map(row=>{if(row.key!==key)return row;const next={...row,...patch};if(patch.facilityId!==undefined)next.departmentId=departments.find(x=>x.parentId===patch.facilityId)?.id||0;return next}));
 const addAllocation=()=>setAllocations(current=>[...current,makeAllocation(Date.now()+current.length)]);
 const removeAllocation=(key:number)=>setAllocations(current=>current.length===1?[makeAllocation()]:current.filter(x=>x.key!==key));
 const resetForm=()=>{setAllocations([makeAllocation()]);setMessage("")};
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setMessage("");if(!productId||allocations.some(x=>!x.facilityId||!x.departmentId||!Number.isInteger(Number(x.requiredQuantity))||Number(x.requiredQuantity)<=0)){setMessage("أكمل المرفق والقسم وأدخل رقم احتياج أكبر من صفر لكل سطر");return}const duplicate=new Set<string>();for(const row of allocations){const key=`${row.facilityId}-${row.departmentId}`;if(duplicate.has(key)){setMessage("لا يمكن تكرار المرفق والقسم لنفس الجهاز داخل الطلب");return}duplicate.add(key)}setSaving(true);try{const r=await apiFetch("/api/planning",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({categoryId,productId,allocations:allocations.map(({facilityId,departmentId,requiredQuantity})=>({facilityId,departmentId,requiredQuantity:Number(requiredQuantity)}))})}),d=await r.json();if(!r.ok)throw new Error(d.error||"تعذر حفظ الاحتياج");setPlans(d.plans);setAllocations([makeAllocation()]);setMessage(`تم حفظ احتياج الجهاز بإجمالي ${enteredTotal}`)}catch(error){setMessage(error instanceof Error?error.message:"تعذر حفظ الاحتياج")}finally{setSaving(false)}};
 const update=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!editing)return;const f=new FormData(e.currentTarget),r=await apiFetch("/api/planning",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:editing.id,requiredQuantity:Number(f.get("requiredQuantity")),notes:f.get("notes")})}),d=await r.json();if(!r.ok){setMessage(d.error);return}setPlans(d.plans);setEditing(null)};
 const remove=async(id:number)=>{if(!confirm("حذف احتياج هذا المرفق والقسم؟"))return;const r=await apiFetch("/api/planning",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({id})});if(r.ok)setPlans(v=>v.filter(x=>x.id!==id))};
 return <section className="planningPage">
  <div className="assetSummary planningSummary"><article><span>إجمالي الاحتياج</span><strong>{totals.need}</strong></article><article><span>الموجود فعليًا</span><strong>{totals.actual}</strong></article><article><span>العجز</span><strong>{totals.shortage}</strong></article><article><span>الفائض</span><strong>{totals.surplus}</strong></article></div>
  <form className="panel groupedPlanningForm" onSubmit={submit}>
   <div className="panelHead"><div><h2>إضافة احتياج مجمّع</h2><p>اختر الجهاز مرة واحدة، ثم أضف المرافق والأقسام والكميات المطلوبة.</p></div><span className="planningTotalBadge">الإجمالي: <strong>{enteredTotal}</strong></span></div>
   <div className="planningItemSelectors"><label>الصنف<select value={categoryId} onChange={e=>setCategoryId(Number(e.target.value))}>{categories.map(x=><option value={x.id} key={x.id}>{x.name} — {x.assetType||"تقني"}</option>)}</select></label><label>الجهاز<select value={productId} onChange={e=>setProductId(Number(e.target.value))} required>{products.filter(x=>x.parentId===categoryId).map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label></div>
   <div className="allocationHead"><span>المرفق</span><span>القسم</span><span>العدد المطلوب</span><span></span></div>
   <div className="allocationRows">{allocations.map((row,index)=><div className="allocationRow" key={row.key}><select aria-label={`المرفق ${index+1}`} value={row.facilityId} onChange={e=>updateAllocation(row.key,{facilityId:Number(e.target.value)})}>{facilities.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select><select aria-label={`القسم ${index+1}`} value={row.departmentId} onChange={e=>updateAllocation(row.key,{departmentId:Number(e.target.value)})} required><option value="">اختر القسم</option>{departments.filter(x=>x.parentId===row.facilityId).map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select><input aria-label={`العدد المطلوب ${index+1}`} type="number" min="1" value={row.requiredQuantity||""} onChange={e=>updateAllocation(row.key,{requiredQuantity:Number(e.target.value)})} required placeholder="0"/><button type="button" className="allocationRemove" onClick={()=>removeAllocation(row.key)} title="حذف السطر">×</button></div>)}</div>
   <div className="groupedPlanningActions"><button type="button" className="addAllocation" onClick={addAllocation}>＋ إضافة مرفق وقسم</button><span>إجمالي الاحتياج المدخل: <strong>{enteredTotal}</strong></span><button type="button" onClick={resetForm}>مسح</button><button className="primary" disabled={saving||!productId}>{saving?"جاري الحفظ...":"حفظ الاحتياج"}</button></div>{message&&<p className="formMessage">{message}</p>}
  </form>
  <article className="panel recordsPanel planningRecords groupedPlanningRecords"><div className="panelHead"><div><h2>خطة الاحتياج حسب الأصناف والأجهزة</h2><p>يظهر الصنف والجهاز بوضوح، مع تفاصيل المرافق والأقسام تحتهما.</p></div><div className="planningFilters"><select value={type} onChange={e=>setType(e.target.value)}><option>الكل</option><option>تقني</option><option>طبي</option></select><select value={facilityFilter} onChange={e=>setFacilityFilter(e.target.value)}><option>الكل</option>{facilities.map(x=><option key={x.id}>{x.name}</option>)}</select></div></div><div className="groupedPlanList">{groups.map(group=><section className="planGroup" key={group.productId}><header><div className="planGroupIdentity"><div className="planGroupMeta"><span className={`typeBadge ${group.assetType==="طبي"?"medical":"technical"}`}>{group.assetType}</span><em>{group.rows.length} مرافق/أقسام</em></div><div className="planGroupNames"><div className="planCategoryName"><small>الصنف</small><strong title={group.categoryName}>{group.categoryName}</strong></div><div className="planDeviceName"><small>الجهاز</small><h3 title={group.productName}>{group.productName}</h3></div></div></div><div className="planGroupTotals"><span>الاحتياج <strong>{group.required}</strong></span><span>الموجود <strong>{group.actual}</strong></span><span>العجز <strong className={group.shortage?"shortageText":"okNumber"}>{group.shortage}</strong></span></div></header><div className="tableWrap"><table><thead><tr><th>المرفق</th><th>القسم</th><th>العدد المطلوب</th><th>الموجود</th><th>العجز</th><th>إجراء</th></tr></thead><tbody>{group.rows.map(x=><tr key={x.id}><td>{x.facilityName}</td><td>{x.departmentName}</td><td>{x.requiredQuantity}</td><td>{x.actualQuantity}</td><td><span className={x.shortage?"shortageNumber":"okNumber"}>{x.shortage}</span></td><td><span className="rowActions"><button onClick={()=>setEditing(x)} title="تعديل">✎</button><button className="deleteAction" onClick={()=>remove(x.id)} title="حذف">⌫</button></span></td></tr>)}</tbody></table></div></section>)}{!groups.length&&<div className="emptyState"><strong>لا توجد خطط مسجلة</strong><span>أضف الاحتياج من النموذج.</span></div>}</div></article>
  {editing&&<div className="overlay" onMouseDown={()=>setEditing(null)}><form className="modal editDefinition" onSubmit={update} onMouseDown={e=>e.stopPropagation()}><div className="modalHead"><div><h2>تعديل الاحتياج</h2><p>{editing.productName} — {editing.facilityName} / {editing.departmentName}</p></div><button type="button" onClick={()=>setEditing(null)}>×</button></div><label>العدد المطلوب<input name="requiredQuantity" type="number" min="1" defaultValue={editing.requiredQuantity} required/></label><label>ملاحظات<textarea name="notes" defaultValue={editing.notes}/></label><div className="modalActions"><button type="button" onClick={()=>setEditing(null)}>إلغاء</button><button className="primary">حفظ</button></div></form></div>}
 </section>
}
