"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {apiFetch} from "../lib/api-client";

type Named={id:number;name:string;usefulLifeYears?:number;assetType?:string};
type Child=Named&{parentId:number};
type Entity="facility"|"department"|"category"|"product";

export default function SetupManager({tab,setTab,facilities,departments,categories,products,onUpdate,onDelete,addNamed,addChild}:{tab:string;setTab:(x:string)=>void;facilities:Named[];departments:Child[];categories:Named[];products:Child[];onUpdate:(e:Entity,item:Named|Child)=>void;onDelete:(e:Entity,id:number)=>void;addNamed:(e:FormEvent<HTMLFormElement>,k:"facility"|"category")=>void;addChild:(e:FormEvent<HTMLFormElement>,k:"department"|"product")=>void}){
 const[editing,setEditing]=useState<{entity:Entity;item:Named|Child}|null>(null),[error,setError]=useState(""),[masterSearch,setMasterSearch]=useState(""),[childSearch,setChildSearch]=useState(""),[masterPage,setMasterPage]=useState(1),[childPage,setChildPage]=useState(1),[childPageSize,setChildPageSize]=useState(10);
 const isFacilities=tab==="المرافق والأقسام",masters=isFacilities?facilities:categories,children=isFacilities?departments:products,masterEntity:Entity=isFacilities?"facility":"category",childEntity:Entity=isFacilities?"department":"product";
 const masterPageSize=6;
 const filteredMasters=useMemo(()=>masters.filter(x=>x.name.toLowerCase().includes(masterSearch.trim().toLowerCase())),[masters,masterSearch]);
 const filteredChildren=useMemo(()=>children.filter(x=>{const parent=masters.find(p=>p.id===x.parentId)?.name||"";return`${x.name} ${parent}`.toLowerCase().includes(childSearch.trim().toLowerCase())}),[children,masters,childSearch]);
 const masterPages=Math.max(1,Math.ceil(filteredMasters.length/masterPageSize)),childPages=Math.max(1,Math.ceil(filteredChildren.length/childPageSize));
 const visibleMasters=filteredMasters.slice((masterPage-1)*masterPageSize,masterPage*masterPageSize),visibleChildren=filteredChildren.slice((childPage-1)*childPageSize,childPage*childPageSize);
 useEffect(()=>{setMasterPage(1);setChildPage(1);setMasterSearch("");setChildSearch("")},[tab]);
 useEffect(()=>{if(masterPage>masterPages)setMasterPage(masterPages)},[masterPage,masterPages]);
 useEffect(()=>{if(childPage>childPages)setChildPage(childPages)},[childPage,childPages]);
 const update=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!editing)return;const f=new FormData(e.currentTarget),payload={entity:editing.entity,id:editing.item.id,name:String(f.get("name")||"").trim(),parentId:Number(f.get("parentId"))||undefined,usefulLifeYears:editing.entity==="category"?Number(f.get("usefulLifeYears")):undefined,assetType:editing.entity==="category"?String(f.get("assetType")||"تقني"):undefined};try{const r=await apiFetch("/api/setup",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}),d=await r.json();if(!r.ok)throw new Error(d.error);onUpdate(editing.entity,d.item);setEditing(null);setError("")}catch(x){setError(x instanceof Error?x.message:"تعذر التعديل")}};
 const remove=async(entity:Entity,item:Named)=>{if(!confirm(`هل تريد حذف «${item.name}»؟ لا يمكن التراجع عن الحذف.`))return;try{const r=await apiFetch("/api/setup",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({entity,id:item.id})}),d=await r.json();if(!r.ok)throw new Error(d.error);onDelete(entity,item.id);setError("")}catch(x){setError(x instanceof Error?x.message:"تعذر الحذف")}};
 return <section className="setupPage">
  <div className="setupTabs"><button className={isFacilities?"active":""} onClick={()=>setTab("المرافق والأقسام")}>⌂ المرافق والأقسام</button><button className={!isFacilities?"active":""} onClick={()=>setTab("الأصناف والأجهزة")}>▣ الأصناف والأجهزة</button></div>
  {error&&<div className="setupError">⚠ {error}</div>}
  <div className="setupGrid">
   <article className="panel masterPanel"><div className="panelHead"><div><h2>{isFacilities?"المرافق":"أصناف الأصول"}</h2><p>{isFacilities?"المستشفيات والمراكز والمباني":"التصنيف الرئيسي والعمر الافتراضي"}</p></div><span className="countBadge">{masters.length}</span></div>
    <form className={`quickAdd ${!isFacilities?"categoryAdd":""}`} onSubmit={e=>addNamed(e,isFacilities?"facility":"category")}><label className="quickField"><span>{isFacilities?"اسم المرفق":"اسم الصنف"}</span><input name="name" required placeholder={isFacilities?"أدخل اسم المرفق الجديد":"أدخل اسم الصنف كاملًا"}/></label>{!isFacilities&&<label className="quickField"><span>نوع الجهاز</span><select name="assetType" defaultValue="تقني"><option>تقني</option><option>طبي</option></select></label>}{!isFacilities&&<label className="quickField lifeInput"><span>العمر الافتراضي</span><div><input name="usefulLifeYears" type="number" min="1" max="100" defaultValue="5" required/><b>سنة</b></div></label>}<button className="primary">＋ إضافة الصنف</button></form>
    <div className="listToolbar"><label>⌕<input value={masterSearch} onChange={e=>{setMasterSearch(e.target.value);setMasterPage(1)}} placeholder={isFacilities?"بحث في المرافق...":"بحث في الأصناف..."}/></label><span>{filteredMasters.length} نتيجة</span></div>
    <div className="masterList">{visibleMasters.map(x=><div className="masterRow" key={x.id}><span className="listIcon">{isFacilities?"⌂":"▣"}</span><div className="masterDetails"><strong title={x.name}>{x.name}</strong><small>{isFacilities?`${children.filter(d=>d.parentId===x.id).length} أقسام`:`${x.assetType||"تقني"} — ${x.usefulLifeYears||5} سنوات`}</small></div><span className="rowActions"><button title="تعديل" onClick={()=>setEditing({entity:masterEntity,item:x})}>✎</button><button className="deleteAction" title="حذف" onClick={()=>remove(masterEntity,x)}>⌫</button></span></div>)}{!visibleMasters.length&&<div className="compactEmpty">لا توجد نتائج مطابقة</div>}</div>
    <Pager page={masterPage} pages={masterPages} total={filteredMasters.length} pageSize={masterPageSize} onChange={setMasterPage}/>
   </article>
   <article className="panel childPanel"><div className="panelHead"><div><h2>{isFacilities?"الأقسام التابعة":"الأجهزة التابعة"}</h2><p>{isFacilities?"اربط كل قسم بالمرفق الصحيح":"اربط كل جهاز بصنف الأصل الصحيح"}</p></div><span className="countBadge">{children.length}</span></div><form className="quickAdd childForm" onSubmit={e=>addChild(e,isFacilities?"department":"product")}><label className="quickField"><span>{isFacilities?"المرفق":"الصنف"}</span><select name="parentId">{masters.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label className="quickField"><span>{isFacilities?"اسم القسم":"اسم الجهاز"}</span><input name="name" required placeholder={isFacilities?"أدخل اسم القسم الجديد":"أدخل اسم الجهاز أو الموديل"}/></label><button className="primary">＋ إضافة {isFacilities?"القسم":"الجهاز"}</button></form><div className="listToolbar"><label>⌕<input value={childSearch} onChange={e=>{setChildSearch(e.target.value);setChildPage(1)}} placeholder={isFacilities?"بحث في الأقسام والمرافق...":"بحث في الأجهزة والأصناف..."}/></label><span>{filteredChildren.length} نتيجة</span></div><div className={`childTable ${!isFacilities?"deviceTable":""}`}><div className="childRow head"><span>{isFacilities?"القسم":"الجهاز"}</span><span>{isFacilities?"المرفق":"الصنف"}</span><span>الإجراءات</span></div>{visibleChildren.map(x=><div className="childRow" key={x.id}><strong title={x.name}>{x.name}</strong><span className="parentName" title={masters.find(p=>p.id===x.parentId)?.name}>{masters.find(p=>p.id===x.parentId)?.name}</span><span className="rowActions"><button title="تعديل" onClick={()=>setEditing({entity:childEntity,item:x})}>✎</button><button className="deleteAction" title="حذف" onClick={()=>remove(childEntity,x)}>⌫</button></span></div>)}{!visibleChildren.length&&<div className="compactEmpty">لا توجد نتائج مطابقة</div>}</div><Pager page={childPage} pages={childPages} total={filteredChildren.length} pageSize={childPageSize} onChange={setChildPage} pageSizeOptions={[10,20,50]} onPageSizeChange={size=>{setChildPageSize(size);setChildPage(1)}}/></article>
  </div>
  <div className="relationHint"><strong>ترابط البيانات</strong><span>{isFacilities?"لا يمكن حذف مرفق يحتوي على أقسام تابعة حفاظاً على سلامة البيانات.":"يُستخدم العمر الافتراضي للصنف في متابعة دورة حياة جميع العهد التابعة له."}</span></div>
  {editing&&<div className="overlay" onMouseDown={()=>setEditing(null)}><form className="modal editDefinition" onSubmit={update} onMouseDown={e=>e.stopPropagation()}><div className="modalHead"><div><h2>تعديل التعريف</h2><p>سيتم تحديث البيانات في جميع قوائم النظام</p></div><button type="button" onClick={()=>setEditing(null)}>×</button></div><label>الاسم<input name="name" defaultValue={editing.item.name} required/></label>{editing.entity==="category"&&<><label>نوع الأصل<select name="assetType" defaultValue={editing.item.assetType||"تقني"}><option>تقني</option><option>طبي</option></select></label><label>العمر الافتراضي للصنف (بالسنوات)<input name="usefulLifeYears" type="number" min="1" max="100" defaultValue={editing.item.usefulLifeYears||5} required/></label></>}{"parentId" in editing.item&&<label>{isFacilities?"المرفق التابع له":"صنف الأصل"}<select name="parentId" defaultValue={editing.item.parentId}>{masters.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label>}<div className="modalActions"><button type="button" onClick={()=>setEditing(null)}>إلغاء</button><button className="primary">حفظ التعديل</button></div></form></div>}
 </section>;
}

function Pager({page,pages,total,pageSize,onChange,pageSizeOptions,onPageSizeChange}:{page:number;pages:number;total:number;pageSize:number;onChange:(page:number)=>void;pageSizeOptions?:number[];onPageSizeChange?:(size:number)=>void}){const start=total?(page-1)*pageSize+1:0,end=Math.min(page*pageSize,total);return <div className="listPager"><span>عرض {start}–{end} من {total}</span>{pageSizeOptions&&onPageSizeChange&&<label>عدد الأجهزة في الصفحة<select value={pageSize} onChange={e=>onPageSizeChange(Number(e.target.value))}>{pageSizeOptions.map(size=><option key={size} value={size}>{size}</option>)}</select></label>}<div><button type="button" disabled={page===1} onClick={()=>onChange(page-1)}>السابق</button><b>{page} / {pages}</b><button type="button" disabled={page===pages} onClick={()=>onChange(page+1)}>التالي</button></div></div>}
