"use client";
import {FormEvent,useState} from "react";
import {apiFetch} from "../lib/supabase-client";

type Named={id:number;name:string;usefulLifeYears?:number};
type Child=Named&{parentId:number};
type Entity="facility"|"department"|"category"|"product";

export default function SetupManager({tab,setTab,facilities,departments,categories,products,onUpdate,onDelete,addNamed,addChild}:{tab:string;setTab:(x:string)=>void;facilities:Named[];departments:Child[];categories:Named[];products:Child[];onUpdate:(e:Entity,item:Named|Child)=>void;onDelete:(e:Entity,id:number)=>void;addNamed:(e:FormEvent<HTMLFormElement>,k:"facility"|"category")=>void;addChild:(e:FormEvent<HTMLFormElement>,k:"department"|"product")=>void}){
 const[editing,setEditing]=useState<{entity:Entity;item:Named|Child}|null>(null),[error,setError]=useState("");
 const isFacilities=tab==="المرافق والأقسام",masters=isFacilities?facilities:categories,children=isFacilities?departments:products,masterEntity:Entity=isFacilities?"facility":"category",childEntity:Entity=isFacilities?"department":"product";
 const update=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!editing)return;const f=new FormData(e.currentTarget),payload={entity:editing.entity,id:editing.item.id,name:String(f.get("name")||"").trim(),parentId:Number(f.get("parentId"))||undefined,usefulLifeYears:editing.entity==="category"?Number(f.get("usefulLifeYears")):undefined};try{const r=await apiFetch("/api/setup",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}),d=await r.json();if(!r.ok)throw new Error(d.error);onUpdate(editing.entity,d.item);setEditing(null);setError("")}catch(x){setError(x instanceof Error?x.message:"تعذر التعديل")}};
 const remove=async(entity:Entity,item:Named)=>{if(!confirm(`هل تريد حذف «${item.name}»؟ لا يمكن التراجع عن الحذف.`))return;try{const r=await apiFetch("/api/setup",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({entity,id:item.id})}),d=await r.json();if(!r.ok)throw new Error(d.error);onDelete(entity,item.id);setError("")}catch(x){setError(x instanceof Error?x.message:"تعذر الحذف")}};
 return <section className="setupPage">
  <div className="setupTabs"><button className={isFacilities?"active":""} onClick={()=>setTab("المرافق والأقسام")}>⌂ المرافق والأقسام</button><button className={!isFacilities?"active":""} onClick={()=>setTab("الأصناف والمنتجات")}>▣ الأصناف والمنتجات</button></div>
  {error&&<div className="setupError">⚠ {error}</div>}
  <div className="setupGrid">
   <article className="panel masterPanel"><div className="panelHead"><div><h2>{isFacilities?"المرافق":"أصناف الأصول"}</h2><p>{isFacilities?"المستشفيات والمراكز والمباني":"التصنيف الرئيسي والعمر الافتراضي"}</p></div><span className="countBadge">{masters.length}</span></div>
    <form className={`quickAdd ${!isFacilities?"categoryAdd":""}`} onSubmit={e=>addNamed(e,isFacilities?"facility":"category")}><input name="name" required placeholder={isFacilities?"اسم المرفق الجديد":"اسم الصنف الجديد"}/>{!isFacilities&&<label className="lifeInput"><span>العمر الافتراضي</span><input name="usefulLifeYears" type="number" min="1" max="100" defaultValue="5" required/><b>سنة</b></label>}<button className="primary">＋ إضافة</button></form>
    <div className="masterList">{masters.map(x=><div key={x.id}><span className="listIcon">{isFacilities?"⌂":"▣"}</span><strong>{x.name}</strong><small>{isFacilities?`${children.filter(d=>d.parentId===x.id).length} أقسام`:`${x.usefulLifeYears||5} سنوات`}</small><span className="rowActions"><button title="تعديل" onClick={()=>setEditing({entity:masterEntity,item:x})}>✎</button><button className="deleteAction" title="حذف" onClick={()=>remove(masterEntity,x)}>⌫</button></span></div>)}</div>
   </article>
   <article className="panel childPanel"><div className="panelHead"><div><h2>{isFacilities?"الأقسام التابعة":"المنتجات التابعة"}</h2><p>{isFacilities?"اربط كل قسم بالمرفق الصحيح":"اربط كل منتج بصنف الأصل الصحيح"}</p></div><span className="countBadge">{children.length}</span></div><form className="quickAdd childForm" onSubmit={e=>addChild(e,isFacilities?"department":"product")}><select name="parentId">{masters.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select><input name="name" required placeholder={isFacilities?"اسم القسم الجديد":"اسم المنتج أو الموديل"}/><button className="primary">＋ إضافة</button></form><div className="childTable"><div className="childRow head"><span>{isFacilities?"القسم":"المنتج"}</span><span>{isFacilities?"المرفق":"الصنف"}</span><span>الإجراءات</span></div>{children.map(x=><div className="childRow" key={x.id}><strong>{x.name}</strong><span>{masters.find(p=>p.id===x.parentId)?.name}</span><span className="rowActions"><button title="تعديل" onClick={()=>setEditing({entity:childEntity,item:x})}>✎</button><button className="deleteAction" title="حذف" onClick={()=>remove(childEntity,x)}>⌫</button></span></div>)}</div></article>
  </div>
  <div className="relationHint"><strong>ترابط البيانات</strong><span>{isFacilities?"لا يمكن حذف مرفق يحتوي على أقسام تابعة حفاظاً على سلامة البيانات.":"يُستخدم العمر الافتراضي للصنف في متابعة دورة حياة جميع العهد التابعة له."}</span></div>
  {editing&&<div className="overlay" onMouseDown={()=>setEditing(null)}><form className="modal editDefinition" onSubmit={update} onMouseDown={e=>e.stopPropagation()}><div className="modalHead"><div><h2>تعديل التعريف</h2><p>سيتم تحديث البيانات في جميع قوائم النظام</p></div><button type="button" onClick={()=>setEditing(null)}>×</button></div><label>الاسم<input name="name" defaultValue={editing.item.name} required/></label>{editing.entity==="category"&&<label>العمر الافتراضي للصنف (بالسنوات)<input name="usefulLifeYears" type="number" min="1" max="100" defaultValue={editing.item.usefulLifeYears||5} required/></label>}{"parentId" in editing.item&&<label>{isFacilities?"المرفق التابع له":"صنف الأصل"}<select name="parentId" defaultValue={editing.item.parentId}>{masters.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label>}<div className="modalActions"><button type="button" onClick={()=>setEditing(null)}>إلغاء</button><button className="primary">حفظ التعديل</button></div></form></div>}
 </section>;
}
