"use client";
import {FormEvent,useEffect,useState} from "react";
const logo="/prcs-logo-original.png";
export default function LoginPage(){
 const[showPassword,setShowPassword]=useState(false),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[setup,setSetup]=useState(false);
 useEffect(()=>{fetch("/api/auth/me").then(r=>{if(r.ok)location.replace("/")});fetch("/api/auth/bootstrap").then(r=>r.json()).then(d=>setSetup(Boolean(d.needsSetup))).catch(()=>{})},[]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");const f=new FormData(e.currentTarget),r=await fetch("/api/auth/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({username:f.get("username"),password:f.get("password"),remember:f.get("remember")==="on"})}),d=await r.json();setBusy(false);if(!r.ok){setMessage(d.error||"تعذر تسجيل الدخول");return}location.replace("/")}
 async function bootstrap(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");const f=new FormData(e.currentTarget);if(f.get("password")!==f.get("confirm")){setBusy(false);setMessage("كلمتا المرور غير متطابقتين");return}const r=await fetch("/api/auth/bootstrap",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email:f.get("email"),username:f.get("username"),password:f.get("password"),setupToken:f.get("setupToken")})}),d=await r.json();setBusy(false);if(!r.ok){setMessage(d.error||"تعذرت التهيئة");return}setSetup(false);setMessage("تم تجهيز حساب المدير. يمكنكِ تسجيل الدخول الآن.")}
 const identity=<section className="loginIdentity" aria-label="هوية النظام"><div className="loginIdentityInner"><img className="prcsLogo loginSeal" src={logo} alt="شعار جمعية الهلال الأحمر الفلسطيني"/><p className="loginKicker">جمعية الهلال الأحمر الفلسطيني</p><h1>إدارة العهد التقنية</h1><p className="loginIntro">نظام موحّد لتسجيل ومتابعة الأصول والعهد وحركتها بين المرافق والأقسام.</p><div className="loginFeatures"><span><i>✓</i> متابعة دقيقة لكل أصل</span><span><i>✓</i> سجل كامل للتسليم والنقل</span><span><i>✓</i> صلاحيات حسب دور المستخدم</span></div></div><small>قسم تكنولوجيا المعلومات</small></section>;
 return <main className="loginPage" dir="rtl">{identity}<section className="loginFormSide">{setup?<form className="loginCard" onSubmit={bootstrap}><img className="prcsLogo mobileLoginMark" src={logo} alt="شعار الهلال الأحمر الفلسطيني"/><header><span>تهيئة لمرة واحدة</span><h2>تجهيز دخول مدير النظام</h2><p>أدخلي بريد مدير النظام الموجود حاليًا، ثم اختاري اسم مستخدم وكلمة مرور محليين.</p></header><label>بريد المدير<div className="loginInput"><b>✉</b><input name="email" type="email" required/></div></label><label>اسم المستخدم<div className="loginInput"><b>●</b><input name="username" minLength={3} required autoComplete="username"/></div></label><label>كلمة المرور<div className="loginInput"><b>●</b><input name="password" type="password" minLength={8} required/></div></label><label>تأكيد كلمة المرور<div className="loginInput"><b>●</b><input name="confirm" type="password" minLength={8} required/></div></label><label>رمز التهيئة<div className="loginInput"><b>#</b><input name="setupToken" type="password" required/></div></label><button className="loginSubmit" disabled={busy}>{busy?"جاري التجهيز...":"حفظ بيانات المدير"}</button>{message&&<p className="loginPreviewNote" role="alert">{message}</p>}</form>:<form className="loginCard" onSubmit={submit}><img className="prcsLogo mobileLoginMark" src={logo} alt="شعار الهلال الأحمر الفلسطيني"/><header><span>مرحباً بعودتك</span><h2>تسجيل الدخول</h2><p>أدخل اسم المستخدم وكلمة المرور التي زوّدك بها مدير النظام.</p></header><label>اسم المستخدم<div className="loginInput"><b>●</b><input name="username" required autoComplete="username" placeholder="اسم المستخدم"/></div></label><label>كلمة المرور<div className="loginInput"><b>●</b><input name="password" type={showPassword?"text":"password"} required autoComplete="current-password"/><button type="button" onClick={()=>setShowPassword(v=>!v)}>{showPassword?"إخفاء":"إظهار"}</button></div></label><div className="loginOptions"><label><input name="remember" type="checkbox"/> تذكرني على هذا الجهاز</label></div><button className="loginSubmit" disabled={busy}>{busy?"جاري الدخول...":"دخول إلى النظام"}<span>←</span></button>{message&&<p className="loginPreviewNote" role="alert">{message}</p>}</form>}<footer>© 2026 قسم تكنولوجيا المعلومات — جميع الحقوق محفوظة</footer></section></main>
}
