"use client";
import {FormEvent,useEffect,useState} from "react";
import {supabase} from "../../lib/supabase-client";
const logo="/prcs-logo-original.png";
export default function LoginPage(){
 const[showPassword,setShowPassword]=useState(false),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[mode,setMode]=useState<"login"|"forgot">("login");
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{if(data.session)location.replace("/")})},[]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");const f=new FormData(e.currentTarget),email=String(f.get("email")),password=String(f.get("password"));const{error}=await supabase.auth.signInWithPassword({email,password});setBusy(false);if(error){setMessage("البريد الإلكتروني أو كلمة المرور غير صحيحة.");return}location.replace("/")}
 async function reset(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const email=String(new FormData(e.currentTarget).get("email"));const{error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${location.origin}/reset-password`});setBusy(false);setMessage(error?"تعذر إرسال رابط الاستعادة. حاولي مرة أخرى.":"إذا كان البريد مرتبطًا بحساب، سيصلك رابط الاستعادة خلال دقائق.")}
 return <main className="loginPage" dir="rtl"><section className="loginIdentity" aria-label="هوية النظام"><div className="loginIdentityInner"><img className="prcsLogo loginSeal" src={logo} alt="شعار جمعية الهلال الأحمر الفلسطيني"/><p className="loginKicker">جمعية الهلال الأحمر الفلسطيني</p><h1>إدارة العهد التقنية</h1><p className="loginIntro">نظام موحّد لتسجيل ومتابعة الأصول والعهد وحركتها بين المرافق والأقسام.</p><div className="loginFeatures"><span><i>✓</i> متابعة دقيقة لكل أصل</span><span><i>✓</i> سجل كامل للتسليم والنقل</span><span><i>✓</i> صلاحيات حسب دور المستخدم</span></div></div><small>قسم تكنولوجيا المعلومات</small></section><section className="loginFormSide">{mode==="forgot"?<form className="loginCard" onSubmit={reset}><img className="prcsLogo mobileLoginMark" src={logo} alt="شعار الهلال الأحمر الفلسطيني"/><header><span>استعادة الحساب</span><h2>نسيت كلمة المرور</h2><p>أدخلي بريد الحساب المسجل وسنرسل رابطًا آمنًا لإنشاء كلمة مرور جديدة.</p></header><label>البريد الإلكتروني<div className="loginInput"><b>✉</b><input name="email" type="email" required autoComplete="email" placeholder="name@palestinercs.org"/></div></label><button className="loginSubmit" disabled={busy}>{busy?"جاري الإرسال...":"إرسال رابط الاستعادة"}</button>{message&&<p className="loginPreviewNote" role="status">{message}</p>}<button className="loginBack" type="button" onClick={()=>{setMode("login");setMessage("")}}>العودة إلى تسجيل الدخول</button></form>:<form className="loginCard" onSubmit={submit}><img className="prcsLogo mobileLoginMark" src={logo} alt="شعار الهلال الأحمر الفلسطيني"/><header><span>مرحباً بعودتك</span><h2>تسجيل الدخول</h2><p>أدخل بيانات الحساب التي زوّدك بها مدير النظام.</p></header><label>البريد الإلكتروني<div className="loginInput"><b>✉</b><input name="email" type="email" required placeholder="name@palestinercs.org" autoComplete="email"/></div></label><label>كلمة المرور<div className="loginInput"><b>●</b><input name="password" type={showPassword?"text":"password"} required placeholder="أدخل كلمة المرور" autoComplete="current-password"/><button type="button" onClick={()=>setShowPassword(v=>!v)}>{showPassword?"إخفاء":"إظهار"}</button></div></label><div className="loginOptions"><label><input type="checkbox"/> تذكرني على هذا الجهاز</label><button type="button" onClick={()=>{setMode("forgot");setMessage("")}}>نسيت كلمة المرور؟</button></div><button className="loginSubmit" disabled={busy}>{busy?"جاري الدخول...":"دخول إلى النظام"}<span>←</span></button>{message&&<p className="loginPreviewNote" role="alert">{message}</p>}</form>}<footer>© 2026 قسم تكنولوجيا المعلومات — جميع الحقوق محفوظة</footer></section></main>
}
