import {desc,eq} from "drizzle-orm";
import {getDb} from "../../../db";
import {assetMovements,assets,inventoryChecks,maintenanceRecords} from "../../../db/schema";
import {currentUser,requirePermission} from "../../../lib/auth";
import {canAccessAssetType} from "../../../lib/asset-scope";
import {isSystemAdminRole} from "../../../lib/roles";
const toClient=(a:typeof assets.$inferSelect)=>({id:a.id,code:a.code,product:a.name,category:a.category,assetType:a.assetType,facility:a.site,department:a.custodian,responsible:a.responsible,status:a.status,condition:a.condition,serial:a.serial,createdAt:a.createdAt});
export async function GET(request:Request){try{const actor=await currentUser(request);if(!actor)return Response.json({error:"غير مصرح"},{status:403});const db=await getDb(),rows=await db.select().from(assets).orderBy(desc(assets.id)).limit(1000);return Response.json({assets:rows.filter(row=>canAccessAssetType(actor,row.assetType)).map(toClient)})}catch(e){return Response.json({error:e instanceof Error?e.message:"تعذر تحميل البيانات"},{status:500})}}
export async function POST(request:Request){const actor=await requirePermission(request,"assets");if(!actor)return Response.json({error:"غير مصرح"},{status:403});try{const p=await request.json()as Record<string,string>;for(const key of["code","product","category","facility","department","responsible","serial"])if(!p[key]?.trim())return Response.json({error:`${key} مطلوب`},{status:400});const condition=p.condition?.trim(),assetType=p.assetType?.trim()||"تقني";if(!["جديد","مستخدم"].includes(condition))return Response.json({error:"حالة العهدة غير صحيحة"},{status:400});if(!["تقني","طبي"].includes(assetType)||!canAccessAssetType(actor,assetType))return Response.json({error:"لا تملك صلاحية إضافة أجهزة من هذا النوع"},{status:403});const db=await getDb();const[row]=await db.insert(assets).values({code:p.code.trim(),name:p.product.trim(),category:p.category.trim(),assetType,site:p.facility.trim(),custodian:p.department.trim(),responsible:p.responsible.trim(),serial:p.serial.trim(),status:p.status?.trim()||"يعمل",condition}).returning();return Response.json({asset:toClient(row)},{status:201})}catch(e){return Response.json({error:e instanceof Error?e.message:"تعذر حفظ البيانات"},{status:500})}}
export async function DELETE(request:Request){const actor=await currentUser(request);if(!actor||!isSystemAdminRole(actor.role))return Response.json({error:"حذف العهدة متاح لمدير النظام فقط"},{status:403});try{const{id}=await request.json()as{id?:number},assetId=Number(id);if(!assetId)return Response.json({error:"العهدة غير محددة"},{status:400});const db=await getDb();const[row]=await db.select().from(assets).where(eq(assets.id,assetId)).limit(1);if(!row)return Response.json({error:"العهدة غير موجودة"},{status:404});await db.delete(assetMovements).where(eq(assetMovements.assetId,assetId));await db.delete(maintenanceRecords).where(eq(maintenanceRecords.assetId,assetId));await db.delete(inventoryChecks).where(eq(inventoryChecks.assetId,assetId));await db.delete(assets).where(eq(assets.id,assetId));return Response.json({deleted:true,id:assetId})}catch(e){return Response.json({error:e instanceof Error?e.message:"تعذر حذف العهدة"},{status:500})}}
